id: A497F5486
title: 'The Sun of Samantabhadra’s Realm: The Quintessence of Oceanic Prayers of Aspiration'
type: translation
pechas:
- ID5E9188A
- I11C5B277
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:29.657065
  last_modified_at: 2023-01-04 12:49:29.657084
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  ID5E9188A/7286: 9BB7
  I11C5B277/7154: 9BB7
